version: '3'
services:
    db:
        build: ./postgres
        user: root
        environment:
            POSTGRES_PASSWORD: secret_postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: goblog
    app:
        build: .
        links:
            - db
        ports:
            - "8080:8080"
        depends_on:
            - "db"
        links:
            - "db"
        command: ./go-blog
