version: '3'
services:
    db:
        image: postgres:12-alpine
        user: root
        environment:
            POSTGRES_PASSWORD: secret_postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: goblog
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d:z
    app:
        build: .
        links:
            - "db"
        ports:
            - "8080:8080"
        depends_on:
            - "db"
