#!/bin/sh

CONTAINER_DB_FILENAME=Dockerfile.db
CONTAINER_DB_IMAGE_NAME=postgres-goblog
CONTAINER_DB_NAME=goblog-db
LOCALHOST=127.0.0.1
DB_PORT=5432

podman build -t $CONTAINER_DB_IMAGE_NAME -f $CONTAINER_DB_FILENAME
podman run --name $CONTAINER_DB_NAME -d -P -p $LOCALHOST:$DB_PORT:$DB_PORT $CONTAINER_DB_IMAGE_NAME
